;aiu;

[Genius ETM 13.0.2.78]
Name = Genius ETM 13.0.2.78
URL = https://update.geniuserp.com/ETM/13.0.2/Genius+ETM+Setup.exe?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly91cGRhdGUuZ2VuaXVzZXJwLmNvbS9FVE0vMTMuMC4yL0dlbml1cytFVE0rU2V0dXAuZXhlIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxODkzNDU2MDAwfX19XX0_&Signature=T-faXMq1rb8Ui3Ua-p-Oy2H1V44s2Uqqt2GDCpYCDOsHjc~6DqZt-jT1pH22ttN7pwCkbpJv0Gutw-CMKUGsRCmaiHcXZE2DwakCMlTZUTzyDhmkU78-tUge-fkqYQ2NNOHTgYQeBR0ZMwq2dppjLI2fyc6S6yl1xgEU3jw13n5a~ClTaO2aiRdGkarfMLmIA-cnTrwplCgd2BAau4Lp~VJZWOn16prt6b6cNagu9j7oEDFFUyfF2iFJXobHXVH-s8k8HoKvXRxkO8nqxl9vDmKqxDTkSTnNAsbblSYVOyRmGCa2hojO-I6oPQSaWnn6~NcBOCHnZXtRLYanePE70g__&Key-Pair-Id=APKAJTJHAY5ZYNPMNI4A
Size = 33811619
ServerFileName = Genius ETM Setup.exe
Flags = Critical
RegistryKey = HKUD\Software\Genius Solutions\Genius ETM\Version
Version = 13.0.2.78

